### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by positlabs** [sketchpunklabs/ossos#11]
I tried to run the examples after cloning and running npm install, but I'm not sure what the process is to set up the dev environment. 

I'm getting this error when I try to run `build` or `preview-site`

```
failed to load config from /Users/josh/Downloads/ossos-main/vite.config.js
error when starting preview server:
Error: Build failed with 1 error:
**node_modules/esbuild/lib/main.js:1336:27: ERROR: [plugin: externalize-deps] Missing "./dist/plugin.js" export in "vite-plugin-list-directory-contents" package**
    at failureErrorWithLog (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/josh/Downloads/ossos-main/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
```

Ultimately, I'm just trying to check out the running examples. Are they hosted somewhere?

**Comment by sketchpunk** [comment]
Sorry neither of those work. You can use "npm run dev" instead.  Also look in the /examples/_res/_setup.txt, you'll need to clone the res repo into it to get access to all the meshes I've made for testing things out.

Sorry for the setup, in the next version I'm hoping to clean up this stuff & make a separate repo to run all the examples with github pages.

**Comment by positlabs** [comment]
Thanks for the info! But I'm still not able to run the dev command after cloning the _res folder. It still complains about the same missing file. 

```
josh@Joshs-MacBook-Pro ossos-main % npm run dev

> ossos@0.0.3 dev
> vite

✘ [ERROR] [plugin externalize-deps] Missing "./dist/plugin.js" export in "vite-plugin-list-directory-contents" package

```

**Comment by sketchpunk** [comment]
ooh ok. I see the problem. the vite plugin is busted.

If you comment out or just remove line 3:
https://github.com/sketchpunklabs/ossos/blob/main/vite.config.js#L3

And 46, 47, 48, 49
https://github.com/sketchpunklabs/ossos/blob/main/vite.config.js#L46

It should remove the use of the plugin, but you'll lose the ability to browse around the file system threw a browser. That means you'll need to know the web addresses of the files you want to run. I do have an index that links most of the examples, so you can use the following as your starting point :  
/examples/threejs/index.html

**Comment by sketchpunk** [comment]
oh, there is also a "demo" i was trying to put together, you can access it too.
/examples/_demo/index.html

**Comment by positlabs** [comment]
Aha! It's simpler than that, even! Looks like the plugin changed their package structure so you just need to update the import line for the plugin. 

`import { directoryPlugin } from 'vite-plugin-list-directory-contents';`

**Comment by sketchpunk** [comment]
nice. I'll try to update the repo at some point soon.
